services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=task-manager'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
